### ISSUE TITLE
No UserID/UserName without an account 

### ISSUE THREAD

**Issue by Access2IT** [Nikba-Creative-Studio/WHMCS-Telegram-Notifications#1]
No UserID/UserName without an account 

First of all, thank you for creating this module/addon.

Would it be possible to add an email address and name if someone creates a ticket without an account?

**Comment by Nikba-Creative-Studio** [comment]
Hello, thank you for identifying the bug. 
We will resolve the issue within a few days and notify you about the update.

**Comment by Nikba-Creative-Studio** [comment]
@Access2IT Thank you for reporting the issue. 

We have resolved the problem with displaying the name for registered users. 
However, we are unable to display the email address. 
Previously, it was shown, but since the email is considered personal data, several users have requested that email addresses be hidden to protect clients privacy.

![chat](https://github.com/user-attachments/assets/4523e013-da9c-4a28-9a6b-c88108706d64)

**Comment by Access2IT** [comment]
Great thank you
